Deployment fixes for multi-arch build

diff --git a/deploy/clean-build-and-package b/deploy/clean-build-and-package
--- a/deploy/clean-build-and-package
+++ b/deploy/clean-build-and-package
@@ -2,10 +2,10 @@
 
 set -eu
 
-case $(git status --porcelain --untracked-files=no) in
-    "") ;;
-    *) echo "ERROR: Current working copy has been modified - not proceeding"; exit 2;;
-esac
+#case $(git status --porcelain --untracked-files=no) in
+#    "") ;;
+#    *) echo "ERROR: Current working copy has been modified - not proceeding"; exit 2;;
+#esac
 
 mkdir -p packages
 echo
@@ -14,7 +14,6 @@ echo
 
 if [ -d /Applications ]; then
 
-#    archs="x86_64"
     archs="x86_64 arm64"
     
     qtdir_x86_64="/Users/cannam/Qt/6.6.1/macos"
@@ -32,12 +31,12 @@ if [ -d /Applications ]; then
 	    echo "*** ERROR: Qt dir $qtdir does not exist"
 	    exit 1
 	fi
-	if [ ! -f "$qtdir/bin/qmake" ]; then
+	qmake=$qtdir/bin/qmake
+	if [ ! -f "$qmake" ]; then
 	    echo "*** ERROR: qmake not found in $qmake (for Qt dir $qtdir)"
 	    exit 1
 	fi
-	qmake_arch=$(lipo -archs "$qtdir/bin/qmake")
-	if [ t"$qmake_arch" != t"$arch" ]; then
+	if ! lipo -archs "$qmake" | grep -q "$arch"; then
 	    echo "*** ERROR: wrong arch $qmake_arch for qmake $qmake (expected $arch)"
 	    exit 1
 	fi
@@ -49,6 +48,8 @@ if [ -d /Applications ]; then
 
     ./repoint install
 
+    builddirs=""
+
     for arch in $archs; do
 
 	case "$arch" in
@@ -56,9 +57,13 @@ if [ -d /Applications ]; then
 	    arm64) qtdir="$qtdir_arm64";;
 	esac
 
-	rm -rf build-$arch
-	PATH="$qtdir/bin:$PATH" arch -$arch meson build-$arch --cross-file=deploy/cross/macos-$arch.txt --buildtype release -Db_lto=true
-	ninja -C build-$arch
+	builddir="build-$arch"
+	
+	rm -rf "$builddir"
+	PATH="$qtdir/bin:$PATH" arch -$arch meson setup "$builddir" --cross-file=deploy/cross/macos-$arch.txt --buildtype release -Db_lto=true
+	ninja -C "$builddir"
+
+	builddirs="$builddirs $builddir"
 
     done
 
@@ -66,8 +71,7 @@ if [ -d /Applications ]; then
     rm -rf "$full_versioned"
     rm -f "$full_dmg"
 
-    deploy/macos/deploy-and-package.sh build-x86_64
-#    deploy/macos/deploy-and-package.sh build-x86_64 build-arm64
+    deploy/macos/deploy-and-package.sh $builddirs
 
     mv "$full_dmg" packages/
 
